# Generated by Django 5.0.6 on 2026-06-26 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('book_name', models.CharField(help_text='e.g. volume1 / volume2', max_length=100)),
                ('chapter', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('num_questions', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False, help_text='Students only see published + ready quizzes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.PositiveSmallIntegerField()),
                ('steps', models.TextField(blank=True)),
                ('chapter', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['question_no', 'id'],
                'unique_together': {('quiz', 'question_no')},
            },
        ),
    ]
