# Generated by Django 5.0.6 on 2026-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
