# Generated by Django 5.0.6 on 2026-06-27 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reference_pdf',
            field=models.FileField(blank=True, help_text='Optional PDF of previous questions, for reference.', null=True, upload_to='quiz_reference_pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
